plugins {
    id 'com.android.application'
}

android {
    namespace 'net.stella.deeix.chat'
    compileSdk 35

    defaultConfig {
        applicationId 'net.stella.deeix.chat'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
